name: xray-analysis
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python
  - pip
  - pytorch
  - torchvision
  - pinecone
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  - pillow
  - joblib
  - pip:
      - opencv-python
      - albumentations
